env:
  grid_size: 10
  obstacles: 5
  agents: 3
  obs_radius: 1
  reward_type: 1
  seed: 25

ql:
  epsilon: 0.8
  decay: 0.99
  alpha: 0.01
  gamma: 0.6
  episodes: 1050

rnd:
  grid_render: True
  obs_render: False
  grayscale: False
  sleep: 0

plt:
  regression_type: lin  # lin/quad/exp
  