env:
  grid_size: 10
  obstacles: 0
  agents: 6
  obs_radius: 1
  reward_type: 1
  seed: 26

ql:
  epsilon: 0.95
  decay: 0.999
  alpha: 0.1
  gamma: 0.6
  episodes: 2

rnd:
  grid_render: False
  grid_obs_render: False
  obs_render: False
  grayscale: False
  sleep: 0

plt:
  regression_type: null  # null/lin/quad/exp
  
