env:
  grid_size: 23
  obstacles: 20
  agents: 6
  obs_radius: 3
  reward_type: 1
  seed: 26

ql:
  epsilon: 0.95
  decay: 0.999
  alpha: 0.1
  gamma: 0.6
  episodes: 6000

rnd:
  grid_render: False
  grid_obs_render: False
  obs_render: False
  grayscale: False
  sleep: 0

plt:
  regression_type: null  # null/lin/quad/exp
  
