env:
  grid_size: 12
  obstacles: 0
  agents: 3
  obs_radius: 2
  reward_type: 1
  seed: 25

ql:
  epsilon: 0.8
  decay: 0.99
  alpha: 0.01
  gamma: 0.6
  episodes: 1000

rnd:
  grid_render: True
  grid_obs_render: True
  obs_render: False
  grayscale: False
  sleep: 1

plt:
  regression_type: null  # null/lin/quad/exp
  
