env:
  grid_size: 12
  obstacles: 15
  agents: 5
  obs_radius: 2
  reward_type: 1
  seed: 1111

ql:
  epsilon: 0.8
  decay: 0.99
  alpha: 0.01
  gamma: 0.6
  episodes: 1000

rnd:
  grid_render: False
  grid_obs_render: True
  obs_render: False
  grayscale: False
  sleep: 0

plt:
  regression_type: null  # null/lin/quad/exp
  
